version: '3.8'

services:
  kids-store:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./database:/app/database
      - ./uploads:/app/uploads
    restart: unless-stopped

  # Development setup (uncomment to use)
  # kids-store-dev:
  #   build: .
  #   ports:
  #     - "3001:3001"
  #     - "5173:5173"
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=3001
  #   volumes:
  #     - ./database:/app/database
  #     - ./uploads:/app/uploads
  #     - ./frontend/src:/app/frontend/src
  #     - ./backend/src:/app/backend/src
  #   command: npm run dev
  #   restart: unless-stopped 